version: '2'

services:
  nlkt_simple:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django_container
    command: python3 manage.py collectstatic
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: docker exec DOCKERNAME /bin/sh -c "python manage.py collectstatic --noinput"
    volumes:
      - .:/usr/src/app
    environment:
      IN_DOCKER: 1
    ports:
      - "8000:8000"
