version: '2'

services:
  nginx:
    # build: ./lamp
    image: nginx
    volumes:
      - .:/www
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./lamp/src:/lamp/src
      - ./nginx:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.django.conf
      - ./nginx/lamp.conf:/etc/nginx/conf.d/default.lamp.conf
    # command: ./start_lamp.sh
    depends_on:
      - django
    links:
      - php
    ports:
      - "8080:80"


  php:
    build: ./lamp
    volumes:
      - ./lamp/src:/lamp/src
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - mysql

    composer:
      image: "composer"
      volumes:
          - "./www/app:/app"
      command: install

    mysql:
      image: mysql:latest
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password


  django:
    build: ./django
    image: django
    command: ./start_django.sh
    # depends_on:
    #   - db
    volumes:
      - .:/django
    ports:
      - "8000:8000"

  # db:
  #   image: postgres
  #   env_file:
  #     - .env
